.ci/build_docs.sh
.ci/docker/Dockerfile
.ci/docker/build-and-publish-docker-image.sh
.gitlab-ci.yml
clash-protocols.cabal
src/Data/Bifunctor/Extra.hs
src/Protocols.hs
src/Protocols/Df.hs
src/Protocols/Df/Simple.hs
src/Protocols/DfLike.hs
src/Protocols/Plugin.hs
stack.yaml
tests/Tests/Protocols/Plugin.hs

That meant:
* swapping the elements of the result of the circuit function
* downgrading to GHC 8.6, as support for 8.10 is still in the works
* downgrading to Cabal 2.4, to satisfy GHC 8.6
Fixes #2.

Make circuit-notation plugin usable

---

clash-protocols.cabal
src/Test/Tasty/Hedgehog/Extra.hs
stack.yaml

`testProperty` is deprecated, replace it by `testPropertyNamed`.

Fix deprecated testProperty

---

src/Protocols.hs
src/Protocols/Axi4/ReadAddress.hs
src/Protocols/Axi4/ReadData.hs
src/Protocols/Axi4/WriteAddress.hs
src/Protocols/Axi4/WriteData.hs
src/Protocols/Axi4/WriteResponse.hs
src/Protocols/Df.hs
src/Protocols/Hedgehog/Internal.hs
src/Protocols/Internal.hs

The old `Simulate` class (with `driveC`, `sampleC`, and `stallC`) is too specific. This class requires an instance of `Backpressure`, meaning that only protocols where the data on the `Bwd` channel can be generated from a list of Booleans can have a `Simulate` instance. When interesting data goes over the `Bwd` channel this is not the case anymore.
Hence `Simulate` is split up into a new `Simulate` class and a `Drivable` class. The `Drivable` class is the same idea as the old `Simulate` class. The new `Simulate` class provides conversions methods to "simulation types". These conversion methods are used to implement `simulateCircuit`, which converts convenient simulation types (usually a list) to the type accepted by the function in the `Circuit` (usually a function of `Signal`s) and …

Split Simulate into Simulate and Drivable

---

src/Protocols/Axi4/Common.hs
src/Protocols/Axi4/ReadAddress.hs
src/Protocols/Axi4/ReadData.hs
src/Protocols/Axi4/WriteAddress.hs
src/Protocols/Axi4/WriteData.hs
src/Protocols/Axi4/WriteResponse.hs
src/Protocols/Internal.hs

This PR refactors AXI4 types so that they each only need one config type variable. This variable is a struct containing all of the `Bool` and `Nat` values that used to be passed around individually. It also adds a way to grab optional fields polymorphically as a `Maybe` value (`Nothing` if the field is turned off, `Just value` if the field is turned on).

AXI4 Refactor

---

clash-protocols.cabal
src/Protocols/Axi4/Stream.hs
src/Protocols/Axi4/Stream/Axi4Stream.hs
tests/Tests/Protocols/DfConv.hs

This PR adds datatypes and instances (Protocol, Backpressure, Simulate, Drivable, DfLike, Test) for the AXI4-Stream protocol (https://developer.arm.com/documentation/ihi0051/a/Introduction/About-the-AXI4-Stream-protocol).
I'm unsure if the way I implemented DfLike is the right way to go; I wanted the data sent over the channel to be of the form `Vec n Axi4StreamByte`, but DfLike requires any type to be allowed, so I used a type variable `dataType` with the added constraint that `dataType ~ Vec n Axi4StreamByte`.

Add datatypes and instances for AXI4-Stream protocol

---

clash-protocols.cabal
src/Protocols/Avalon/Stream.hs
src/Protocols/Avalon/Stream/AvalonStream.hs
src/Protocols/Internal.hs
tests/Tests/Protocols/DfConv.hs

This PR adds datatypes and instances (Protocol, Backpressure, Simulate, Drivable, DfLike, Test) for the Avalon-Stream protocol.
TODO:

Add datatypes and instances for Avalon stream protocol

---

clash-protocols.cabal
src/Protocols/Avalon/MemMap.hs
src/Protocols/Avalon/MemMap/AvalonMemMap.hs
src/Protocols/DfConv.hs
src/Protocols/Internal.hs
tests/Tests/Protocols.hs
tests/Tests/Protocols/AvalonMemMap.hs
tests/Tests/Protocols/DfConv.hs

This PR adds datatypes and instances (Protocol, Backpressure, Simulate, Drivable, DfLike, Test) for the Avalon Memory-Mapped protocol (http://www1.cs.columbia.edu/~sedwards/classes/2009/4840/mnl_avalon_spec.pdf).
~~It also adds an implementation of the interconnect fabric (needed to connect master and slave ports).~~ The interconnect fabric was more complicated than expected to write & get working for all possible cases. I might open a draft PR with my incomplete version.

Add datatypes and instances for Avalon Memory-Mapped protocol

---

clash-protocols.cabal
src/Protocols/Wishbone/Standard.hs
src/Protocols/Wishbone/Standard/Hedgehog.hs
tests/Tests/Protocols/Wishbone.hs

Renames internal "spec validation" to "lenient validation" and adds a "common sense validation" mode.
The common sense validation mode checks for assumptions that seem sensible but are not part of the Wishbone specification.

add 'common sense' wishbone validation

---

.github/workflows/ci.yml
cabal.project
clash-protocols.cabal
src/Protocols/Avalon/MemMap.hs
src/Protocols/Avalon/Stream.hs
src/Protocols/Axi4/Stream.hs
src/Protocols/Df.hs
src/Protocols/Internal.hs
src/Protocols/Plugin.hs
src/Protocols/Wishbone/Standard/Hedgehog.hs
stack.yaml

This includes the updated `circuit-notation` plugin and some changes regarding deep subsumption.

GHC 9.0 support

---

clash-protocols.cabal
src/Protocols/Axi4/Common.hs
src/Protocols/Axi4/ReadAddress.hs
src/Protocols/Axi4/ReadData.hs
src/Protocols/Axi4/WriteAddress.hs
src/Protocols/Axi4/WriteData.hs
src/Protocols/Axi4/WriteResponse.hs
src/Protocols/DfConv.hs
tests/Tests/Protocols.hs
tests/Tests/Protocols/Avalon.hs
tests/Tests/Protocols/Axi4.hs
tests/Tests/Protocols/DfConv.hs

This PR adds a bunch of small improvements for DfConv and Axi4 related stuff:
- Fixes the AXI4 DfConv instances so that the Write instance doesn't infinite loop and the Read instance doesn't duplicate data
- Adds tests for the AXI4 instances
- Moves the tests around into more sensible filenames
- Renames `GoodAxi4...Config`s to `KnownAxi4...Config`
- Adds some instance derivations to Axi4 files needed to make the tests typecheck
- Adds an `instance DfConv (Reverse a)` and a test to make sure it works

Small improvements for DFConv and Axi4 related stuff

---

src/Protocols/Internal.hs

Two instance declarations were added to `clash-protocols` in 1.7.0.
Previously the conditional inclusion was errornously based on the GHC version.

check for clash-prelude version instead of GHC version

---

src/Protocols/Wishbone.hs
src/Protocols/Wishbone/Standard.hs
src/Protocols/Wishbone/Standard/Hedgehog.hs
tests/Tests/Protocols/Wishbone.hs

Wishbone adjustments

---

.github/workflows/ci.yml
clash-protocols.cabal
src/Protocols/Df.hs
src/Protocols/DfConv.hs
src/Protocols/Hedgehog.hs
src/Protocols/Internal.hs

Increases version bounds to allow for the next generation of Clash dependencies.

Allow newer Clash

---

.ci/build_docs.sh
cabal.project
clash-protocols.cabal
src/Protocols.hs
src/Protocols/Cpp.hs
src/Protocols/Hedgehog/Internal.hs
src/Protocols/Internal.hs
src/Protocols/Internal/TaggedBundle.hs
src/Protocols/Internal/TaggedBundle/TH.hs
src/Protocols/Internal/Units.hs
src/Protocols/Internal/Units/TH.hs
src/Protocols/Plugin.hs
src/Protocols/Plugin/Internal.hs
stack.yaml
tests/Tests/Protocols/Plugin.hs

Bump `circuit-notation` version

---

src/Protocols.hs

It was never meant to be only exported from `.Internal`.

Expose `CSignal` from `Protocols`

---

src/Protocols/Internal.hs
src/Protocols/Wishbone/Standard.hs

Just a `()` means `dom` gets lost, which makes bundeling and unbundeling impossible. This can make it very awkward to use `CSignal` in practise.

Use `Signal dom ()` in `Bwd (CSignal dom a)` again

---

src/Protocols/Df.hs

Currently `registerBwd` fully registers both the forward and backward paths. Which is somewhat misleading given the name. This PR makes it so it only breaks up the path on the backward direction. Which can be done with one register less on the forward path.

Df: `registerBwd` now places only a single register on the data path

---

clash-protocols.cabal
src/Protocols/Internal.hs
src/Protocols/Internal/TH.hs
src/Protocols/Internal/Units/TH.hs

Previously instances were only provided up to arity 4, which was surprisingly low.

Add Protocol instances for tuples up to arity 8

---

src/Protocols.hs

Comes up pretty much instantly when trying to write a `DfConv` instance for protocols where data flows in both directions.

Export `Reverse`

---

.ci/build_docs.sh
clash-protocols.cabal
src/Protocols/Avalon/MemMap.hs
src/Protocols/Avalon/Stream.hs
src/Protocols/Axi4/ReadAddress.hs
src/Protocols/Axi4/ReadData.hs
src/Protocols/Axi4/Stream.hs
src/Protocols/Axi4/WriteAddress.hs
src/Protocols/Axi4/WriteData.hs
src/Protocols/Axi4/WriteResponse.hs
src/Protocols/Df.hs
src/Protocols/Idle.hs
src/Protocols/Internal.hs
src/Protocols/Internal/Classes.hs
src/Protocols/Internal/TH.hs
src/Protocols/Wishbone.hs

Adds typeclasses that enable us to create Circuits that do nothing, can mainly be used to tie off unused inputs.
Useful for example in this case: https://github.com/bittide/bittide-hardware/pull/424/files#diff-bb29a93c87cbea176e39950d009f573873b4eaf327687b90d22a574be5619a05R104-R112

Idle bus typeclasses

---

src/Protocols/Avalon/MemMap.hs
src/Protocols/Avalon/Stream.hs
src/Protocols/Axi4/ReadAddress.hs
src/Protocols/Axi4/ReadData.hs
src/Protocols/Axi4/Stream.hs
src/Protocols/Axi4/WriteAddress.hs
src/Protocols/Df.hs
src/Protocols/Internal/Classes.hs
src/Protocols/Wishbone.hs

`forceResetSanity` ensures combinatorially that a component does not produce data or acknowledge transactions while in Reset.
Prior to this PR, this functionality was only implemented for `Df`.
This pull requests adds a generic version based on the `IdleCircuit` typeclass to be use internally.

Add `forceResetSanity` for all protocols

---

README.md

Update README to use forceResetSanity

---

clash-protocols.cabal
src/Protocols/Avalon/Stream.hs
src/Protocols/Axi4/Stream.hs
src/Protocols/Hedgehog.hs
src/Protocols/Hedgehog/Internal.hs
src/Protocols/Wishbone/Standard/Hedgehog.hs
tests/Tests/Protocols/Df.hs
tests/Tests/Protocols/DfConv.hs

The input length is not always equal to the output length, nor even predictable. Furthermore, some properties might not be interested in the length in the first place.
Fixes #81

Do not verify lengths in `propWithModel`

---

clash-protocols.cabal
src/Protocols/Hedgehog.hs
src/Protocols/Hedgehog/Internal.hs

Adds the ability to specify a wall-clock timeout to one iteration of `propWithModel`. This can help to hone in on specific inputs causing combinatorial loops.

Add `eoTimeoutMs`

---

.github/scripts/all_check.py
.github/workflows/ci.yml

Add `all` check to CI

---

clash-protocols/clash-protocols.cabal

This ensures that the package split introduced in e2f4da3ad5fa9218fd4506c9d433d9adb5c7bfe8 isn't visible to the user.

Reexport Protocols.Plugin from clash-protocols

---

clash-protocols/src/Protocols/Df.hs

This combinator is both necessary for completeness and is useful for tying off unused inputs.

Introduce Protocols.Df.empty

---

clash-protocols/src/Protocols/Df.hs

This consumes all values presented on a 'Df', ignoring them.

Df: Add consume combinator

---

clash-protocols/src/Protocols/Df.hs

Various `Df` combinators are higher-order functions, such as `map` and `filter`. Sometimes it is handy if those combinators are able to handle functions that are wrapped inside of a `Signal`. For example:
```Haskell
arpReceiverC
:: forall (dom :: Domain) (dataWidth :: Nat)
. HiddenClockResetEnable dom
=> KnownNat dataWidth
=> 1 <= dataWidth
=> Signal dom IPv4Address
-> Circuit (PacketStream dom dataWidth EthernetHeader) (Df dom ArpEntry, Df dom ArpLite)
arpReceiverC myIP = circuit $ \ethStream -> do
arpDf <- depacketizeToDfC const -< ethStream
arpDf' <- Df.filterS (isValidArp <$> myIP) -< arpDf
(arpRequests, arpEntries) <- partitionS (isRequest <$> myIP) -< arpDf'
...
```
In this case we want to filter out all invalid ARP packets from a `Df` stream. But such a filter depends on our IPv4 …

Add variants of Df functions that handle function arguments wrapped in signals

---

.github/workflows/ci.yml
format.sh

Paths were broken after separating `clash-protocols` in 2 packages

Fix fourmulu check

---

clash-protocols/src/Protocols/Idle.hs

This enables attaching an idleCircuit to a Vec of protocols and to a Unit type protocol. 
This is useful when using `vecCircuits` to attach multiple slaves to an interconnect.

Add Vec and unit type instances to IdleCircuit

---

clash-protocols/clash-protocols.cabal
clash-protocols/src/Protocols/PacketStream/Base.hs
clash-protocols/src/Protocols/PacketStream/Converters.hs
clash-protocols/src/Protocols/PacketStream/Delay.hs
clash-protocols/src/Protocols/PacketStream/Depacketizers.hs
clash-protocols/src/Protocols/PacketStream/Hedgehog.hs
clash-protocols/src/Protocols/PacketStream/PacketFifo.hs
clash-protocols/src/Protocols/PacketStream/Packetizers.hs
clash-protocols/tests/Tests/Protocols/PacketStream.hs
clash-protocols/tests/Tests/Protocols/PacketStream/AsyncFifo.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Base.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Converters.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Delay.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Depacketizers.hs
clash-protocols/tests/Tests/Protocols/PacketStream/PacketFifo.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Packetizers.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Routing.hs

Adds support for zero-byte transfers in the `PacketStream` protocol. The type of `_last` is updated from `Index dataWidth` to `Index (dataWidth + 1)` and now means "the number of valid bytes in the transfer" instead of "the index of the last valid byte in the transfer".
Note that components are free to refuse zero-byte packets or packets with trailing zero-byte transfers. This should be well-documented. Thus, also added ways to not generate such packets in the test framework. The newly added 'stripTrailingEmptyC' merges trailing zero-byte transfers with the previous one.

PacketStream: support zero-byte transfers.

---

clash-protocols/src/Protocols/Internal.hs
clash-protocols/src/Protocols/Internal/TH.hs

We can use more quotations and less "bare" TH constructions.
This was intended as a change to #117, but it was already merged.

Use more quotations in TH module

---

clash-protocols/clash-protocols.cabal
clash-protocols/src/Protocols/DfConv.hs
clash-protocols/src/Protocols/Internal.hs
clash-protocols/src/Protocols/Vec.hs
clash-protocols/tests/Tests/Protocols.hs
clash-protocols/tests/Tests/Protocols/Vec.hs

Utilties to easily work with vectors of circuits

Add utils for `Circuit (Vec n c) (Vec n c)`

---

.ci/apply_settings.sh
.ci/build_docs.sh
.ci/cabal.project.local
.ci/cabal.project.local.in
.ci/test_cabal.sh
.github/workflows/ci.yml
cabal.project
clash-protocols-base/clash-protocols-base.cabal
clash-protocols/clash-protocols.cabal
clash-protocols/src/Protocols/Avalon/Stream.hs
clash-protocols/src/Protocols/Axi4/ReadAddress.hs
clash-protocols/src/Protocols/Axi4/ReadData.hs
clash-protocols/src/Protocols/Axi4/Stream.hs
clash-protocols/src/Protocols/Axi4/WriteAddress.hs
clash-protocols/src/Protocols/Axi4/WriteData.hs
clash-protocols/src/Protocols/Axi4/WriteResponse.hs
clash-protocols/src/Protocols/Df.hs
clash-protocols/src/Protocols/Internal.hs
clash-protocols/src/Protocols/PacketStream/Hedgehog.hs
clash-protocols/src/Protocols/Wishbone.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Padding.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Routing.hs
stack.yaml

This PR includes the commits of PR #110 (which I initially had not noticed when I opened this PR).
Updates the `circuit-notation` plugin to current master.
`Protocols.Internal` actually contains quite some orphan instances regardless of `clash-prelude` version now.
Rowan or Tim, could you verify I did the right thing in the _Fix partial function warnings in PacketStream_ commit? By the time I got to `makePropPacketArbiter` I was frankly spent and my error message is pretty non-helpful.
Funny thing: `head` has a warning but `last` doesn't. So we could just rewrite every use of `head` to `last . reverse`. For some reason I didn't.

Support GHC 9.8 and GHC 9.10

---

.ci/apply_settings.sh
.ci/build_docs.sh
.ci/cabal.project.local.in
.ci/test_cabal.sh
.github/workflows/ci.yml
clash-protocols-base/clash-protocols-base.cabal
clash-protocols/clash-protocols.cabal
stack.yaml

I noticed a few points where CI could easily be improved a bit. See the individual commit messages for details.
I also bumped the Stack version in `stack.yaml` to the latest LTS.

Small improvements to CI

---

clash-protocols/src/Protocols/Df.hs

The type of `blockRamU` has changed since Clash 1.8.
The `clash-cores` package explicitly targets both Clash 1.8 and Clash master. Since we want to add `clash-protocols` as a dependency to `clash-cores`, we need `clash-protocols` to support Clash master.

Support Clash current master

---

clash-protocols/src/Protocols/Df.hs
clash-protocols/tests/Tests/Protocols/Df.hs

It used to switch the sources even when the current output was not acked.
Fixes #137

Fix Df.roundRobinCollect adherence to the Df proto

---

clash-protocols/src/Protocols/Axi4/Common.hs
clash-protocols/src/Protocols/Axi4/ReadAddress.hs
clash-protocols/src/Protocols/Axi4/WriteAddress.hs
clash-protocols/tests/Tests/Protocols/Axi4.hs

To be honest, I'm not sure why these datatypes did not already have a `BitPack` instance.

AXI: Add `BitPack` instance to all channel signals

---

clash-protocols/tests/Tests/Protocols/Plugin.hs

Per [the documentation](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/pragmas.html#options-ghc-pragma):
> Previous versions of GHC accepted `OPTIONS` rather than `OPTIONS_GHC`, but that is now deprecated.
Additionally, the Haddock module description seemed to refer to the `-fplugin` option rather than actually describing the module, so the comment is moved and made a regular comment instead of a Haddock block. For consistency with the rest of the code base, line comments are used instead of block comments.

Fix use of deprecated OPTIONS pragma

---

.github/workflows/ci.yml

If a push triggers a GitHub Action, it does not have the property `github.head_ref`, leading to an immediate failure. We generally solve this by falling back to `github.run_id`.
Note that if it does fall back to run_id becasue head_ref was unset, the `cancel-in-progress` will not work since the run ID is unique for the run, so there will never be multiple runs in a single concurrency group.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
Additionally, it is now possible to manually trigger a CI run. If the last run for the main branch was so long ago that its caches expired, and you open multiple PR's before merging one, each PR will have to rebuild all dependencies because they only can get their caches from the main …

Fix CI for push events

---

clash-protocols/src/Protocols/Internal.hs

Fixes https://github.com/clash-lang/clash-protocols/issues/149

Make `prod2C` lazy in its arguments + Add `prod3C` and `prod4C`

---

clash-protocols/src/Protocols/Df.hs
clash-protocols/src/Protocols/PacketStream/Converters.hs
clash-protocols/src/Protocols/PacketStream/Depacketizers.hs
clash-protocols/src/Protocols/PacketStream/Packetizers.hs
clash-protocols/src/Protocols/PacketStream/Padding.hs
clash-protocols/src/Protocols/PacketStream/Routing.hs

Many streaming components currently insist that the `O_READY` signal takes on a particular value when `I_VALID` is driven low. This introduces a combinational path between `I_VALID` and `O_READY` on the same streaming interface, which is not disallowed by any protocol specifications (as there must not be a combinational path between `I_READY` and `O_VALID`), but it is unnecessary. Driving `O_READY` as `X` (don't care) when `I_VALID` is driven low removes these paths, which is likely to ease timing closure. Especially since there is usually already a lot of logic driving these control signals.

Optimize ready signaling

---

clash-protocols/clash-protocols.cabal
clash-protocols/src/Data/List/Extra.hs
clash-protocols/src/Protocols/Wishbone.hs
clash-protocols/src/Protocols/Wishbone/Standard/Hedgehog.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Base.hs
clash-protocols/tests/Tests/Protocols/PacketStream/Padding.hs
clash-protocols/tests/Util.hs

The implementation of `hasBusActivity` was wrong, `filterTransactions` bloats the API because it's the same as `filter hasBusActivity` and `takeWhileAnyInWindow` is very generic and useful outside of wishbone tests

Small wb related changes

---

clash-protocols-base/clash-protocols-base.cabal

It needs neither the `TypeLits` plugins nor a custom build-type.

Simplify `clash-protocols-base.cabal`

---

.github/workflows/ci.yml

Previous implementation contained a bunch of references to non-existing variables.

Simplify CI caching logic
